# Generated by Django 6.0.3 on 2026-04-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cus_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=15)),
                ('Country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Customer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('Hotel_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Hotel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Reservation_ID', models.IntegerField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_Method', models.CharField(max_length=20)),
                ('Payment_Date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Payment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('Reservation_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cus_ID', models.IntegerField()),
                ('Room_ID', models.IntegerField()),
                ('Check_In_Date', models.DateField()),
                ('Check_Out_Date', models.DateField()),
            ],
            options={
                'db_table': 'Reservation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('Room_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Hotel_ID', models.IntegerField()),
                ('Category_ID', models.IntegerField()),
                ('Status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('Category_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Category_Name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Room_Category',
                'managed': True,
            },
        ),
    ]
